name: arduino-cli / lpc845brk

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/_arduino-cli.yml
    with:
      platform: lpc845brk
