name: fbuild / lpcxpresso845max

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/_fbuild.yml
    with:
      platform: lpcxpresso845max
